[package]
name = "mc-instance"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Installation d'une instance Minecraft : fichiers vanilla puis NeoForge"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures-util.workspace = true
mc-dl = { path = "../mc-dl" }
