#!/usr/bin/env node
/**
 * Does the built CSS still carry the prefix WebKitGTK needs?
 *
 * ## What breaks, and why nothing would say so
 *
 * The launcher's WebKitGTK (2.52.5, `libwebkit2gtk-4.1.so.0.21.9`) exposes
 * ONLY `-webkit-backdrop-filter`: the unprefixed form is absent from the
 * library. Angular doesn't go through autoprefixer — it translates
 * package.json's `browserslist` into esbuild targets, and esbuild is the
 * only one that prefixes. The threshold is exactly Safari 18: above it, it
 * only emits the modern form.
 *
 * Consequence: replacing `safari 17.4` with any newer target — or with
 * Angular's `> 1%` default — makes the prefix disappear, and every
 * `backdrop-blur-*` in the interface stops having any effect AT ALL INSIDE
 * THE WINDOW. The build succeeds, the tests pass, CI is green, and the
 * frosted glass renders flat. Nobody connects that to a `browserslist` line
 * changed three weeks earlier.
 *
 * ## The trap this script also exists to close
 *
 * The design system writes both forms itself, which makes this check less
 * critical than it used to be back when the utilities were generated by a
 * tool. It still matters for the CSS WE write — component styles — where
 * the prefix is never written by hand: esbuild is the one that adds it, and
 * it only does so below Safari 18.
 *
 * Hence the check runs on the COMPILED CSS and not on the sources: a
 * hand-written prefix somewhere would pass the check — esbuild doesn't
 * strip a hand-written prefix — while leaving everything that doesn't have
 * one unprefixed.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUTPUT = fileURLToPath(new URL('../dist/launcher/browser', import.meta.url));

let sheets;
try {
  sheets = readdirSync(OUTPUT).filter((name) => name.endsWith('.css'));
} catch {
  console.error(`No build output under ${OUTPUT}. Run "pnpm build" first.`);
  process.exit(1);
}

if (sheets.length === 0) {
  console.error('The build produced no stylesheet.');
  process.exit(1);
}

const css = sheets.map((name) => readFileSync(join(OUTPUT, name), 'utf8')).join('\n');

const prefixed = css.includes('-webkit-backdrop-filter');
// The regex avoids counting the prefix a second time: it looks for the
// property preceded by anything other than a dash.
const unprefixed = /(^|[^-])backdrop-filter\s*:/.test(css);

if (!unprefixed && !prefixed) {
  console.log(
    '  ~ no backdrop-filter in the built CSS — nothing to check as long\n' +
      '    as no component uses the frosted glass.',
  );
  process.exit(0);
}

if (unprefixed && !prefixed) {
  console.error(
    '\n  ✗ backdrop-filter is emitted WITHOUT the -webkit- prefix.\n' +
      "\n    The launcher's WebKitGTK only knows the prefixed form: all the\n" +
      "    window's frosted glass will render flat, in production only.\n" +
      '\n    Near-certain cause: package.json\'s "browserslist" was changed.\n' +
      "    It must stay under Safari 18 — that's the threshold at which\n" +
      "    esbuild stops prefixing. See this script's comment.\n",
  );
  process.exit(1);
}

console.log('  ✓ -webkit-backdrop-filter present in the built CSS');
